import { WMOInfo } from '../types';

export const WMO_MAP: Record<number, WMOInfo> = {
  0: {
    code: 0,
    label: 'Clear Sky',
    category: 'clear',
    icon: 'Sun',
    bgGradientLight: 'from-amber-500/10 via-orange-500/5 to-white',
    bgGradientDark: 'from-amber-500/10 via-orange-500/5 to-white',
    cardBg: 'bg-amber-50 border-amber-200 text-[#0D0D0D]',
  },
  1: {
    code: 1,
    label: 'Mainly Clear',
    category: 'clear',
    icon: 'SunDim',
    bgGradientLight: 'from-amber-400/10 via-sky-500/5 to-white',
    bgGradientDark: 'from-amber-400/10 via-sky-500/5 to-white',
    cardBg: 'bg-sky-50 border-sky-200 text-[#0D0D0D]',
  },
  2: {
    code: 2,
    label: 'Partly Cloudy',
    category: 'cloudy',
    icon: 'CloudSun',
    bgGradientLight: 'from-slate-100 via-sky-50 to-white',
    bgGradientDark: 'from-slate-100 via-sky-50 to-white',
    cardBg: 'bg-slate-50 border-slate-200 text-[#0D0D0D]',
  },
  3: {
    code: 3,
    label: 'Overcast',
    category: 'cloudy',
    icon: 'Cloud',
    bgGradientLight: 'from-slate-100 via-slate-50 to-white',
    bgGradientDark: 'from-slate-100 via-slate-50 to-white',
    cardBg: 'bg-slate-100 border-slate-300 text-[#0D0D0D]',
  },
  45: {
    code: 45,
    label: 'Foggy',
    category: 'fog',
    icon: 'CloudFog',
    bgGradientLight: 'from-teal-50 via-slate-50 to-white',
    bgGradientDark: 'from-teal-50 via-slate-50 to-white',
    cardBg: 'bg-teal-50 border-teal-200 text-[#0D0D0D]',
  },
  48: {
    code: 48,
    label: 'Depositing Rime Fog',
    category: 'fog',
    icon: 'CloudFog',
    bgGradientLight: 'from-cyan-50 via-slate-50 to-white',
    bgGradientDark: 'from-cyan-50 via-slate-50 to-white',
    cardBg: 'bg-cyan-50 border-cyan-200 text-[#0D0D0D]',
  },
  51: {
    code: 51,
    label: 'Light Drizzle',
    category: 'drizzle',
    icon: 'CloudDrizzle',
    bgGradientLight: 'from-blue-50 via-sky-50 to-white',
    bgGradientDark: 'from-blue-50 via-sky-50 to-white',
    cardBg: 'bg-blue-50 border-blue-200 text-[#0D0D0D]',
  },
  53: {
    code: 53,
    label: 'Moderate Drizzle',
    category: 'drizzle',
    icon: 'CloudDrizzle',
    bgGradientLight: 'from-blue-100/50 via-sky-50 to-white',
    bgGradientDark: 'from-blue-100/50 via-sky-50 to-white',
    cardBg: 'bg-blue-50 border-blue-200 text-[#0D0D0D]',
  },
  55: {
    code: 55,
    label: 'Dense Drizzle',
    category: 'drizzle',
    icon: 'CloudRain',
    bgGradientLight: 'from-blue-100 via-sky-100/50 to-white',
    bgGradientDark: 'from-blue-100 via-sky-100/50 to-white',
    cardBg: 'bg-blue-100 border-blue-300 text-[#0D0D0D]',
  },
  56: {
    code: 56,
    label: 'Light Freezing Drizzle',
    category: 'drizzle',
    icon: 'CloudHail',
    bgGradientLight: 'from-indigo-50 via-slate-50 to-white',
    bgGradientDark: 'from-indigo-50 via-slate-50 to-white',
    cardBg: 'bg-indigo-50 border-indigo-200 text-[#0D0D0D]',
  },
  57: {
    code: 57,
    label: 'Dense Freezing Drizzle',
    category: 'drizzle',
    icon: 'CloudHail',
    bgGradientLight: 'from-indigo-100/60 via-slate-50 to-white',
    bgGradientDark: 'from-indigo-100/60 via-slate-50 to-white',
    cardBg: 'bg-indigo-100 border-indigo-300 text-[#0D0D0D]',
  },
  61: {
    code: 61,
    label: 'Slight Rain',
    category: 'rain',
    icon: 'CloudRain',
    bgGradientLight: 'from-blue-50 via-sky-50 to-white',
    bgGradientDark: 'from-blue-50 via-sky-50 to-white',
    cardBg: 'bg-blue-50 border-blue-200 text-[#0D0D0D]',
  },
  63: {
    code: 63,
    label: 'Moderate Rain',
    category: 'rain',
    icon: 'CloudRain',
    bgGradientLight: 'from-blue-100/60 via-sky-50 to-white',
    bgGradientDark: 'from-blue-100/60 via-sky-50 to-white',
    cardBg: 'bg-blue-100 border-blue-300 text-[#0D0D0D]',
  },
  65: {
    code: 65,
    label: 'Heavy Rain',
    category: 'rain',
    icon: 'CloudRainWind',
    bgGradientLight: 'from-blue-200/50 via-slate-100 to-white',
    bgGradientDark: 'from-blue-200/50 via-slate-100 to-white',
    cardBg: 'bg-blue-100 border-blue-400 text-[#0D0D0D]',
  },
  66: {
    code: 66,
    label: 'Light Freezing Rain',
    category: 'rain',
    icon: 'CloudHail',
    bgGradientLight: 'from-cyan-100/50 via-sky-50 to-white',
    bgGradientDark: 'from-cyan-100/50 via-sky-50 to-white',
    cardBg: 'bg-cyan-50 border-cyan-200 text-[#0D0D0D]',
  },
  67: {
    code: 67,
    label: 'Heavy Freezing Rain',
    category: 'rain',
    icon: 'CloudHail',
    bgGradientLight: 'from-cyan-200/50 via-slate-100 to-white',
    bgGradientDark: 'from-cyan-200/50 via-slate-100 to-white',
    cardBg: 'bg-cyan-100 border-cyan-300 text-[#0D0D0D]',
  },
  71: {
    code: 71,
    label: 'Slight Snow Fall',
    category: 'snow',
    icon: 'CloudSnow',
    bgGradientLight: 'from-sky-100/40 via-slate-50 to-white',
    bgGradientDark: 'from-sky-100/40 via-slate-50 to-white',
    cardBg: 'bg-sky-50 border-sky-200 text-[#0D0D0D]',
  },
  73: {
    code: 73,
    label: 'Moderate Snow Fall',
    category: 'snow',
    icon: 'CloudSnow',
    bgGradientLight: 'from-sky-100 via-slate-100 to-white',
    bgGradientDark: 'from-sky-100 via-slate-100 to-white',
    cardBg: 'bg-sky-100 border-sky-300 text-[#0D0D0D]',
  },
  75: {
    code: 75,
    label: 'Heavy Snow Fall',
    category: 'snow',
    icon: 'Snowflake',
    bgGradientLight: 'from-sky-200/60 via-slate-100 to-white',
    bgGradientDark: 'from-sky-200/60 via-slate-100 to-white',
    cardBg: 'bg-sky-200 border-sky-400 text-[#0D0D0D]',
  },
  77: {
    code: 77,
    label: 'Snow Grains',
    category: 'snow',
    icon: 'Snowflake',
    bgGradientLight: 'from-sky-50 via-slate-50 to-white',
    bgGradientDark: 'from-sky-50 via-slate-50 to-white',
    cardBg: 'bg-sky-50 border-sky-200 text-[#0D0D0D]',
  },
  80: {
    code: 80,
    label: 'Slight Rain Showers',
    category: 'rain',
    icon: 'CloudSunRain',
    bgGradientLight: 'from-sky-100/50 via-amber-50/30 to-white',
    bgGradientDark: 'from-sky-100/50 via-amber-50/30 to-white',
    cardBg: 'bg-sky-50 border-sky-200 text-[#0D0D0D]',
  },
  81: {
    code: 81,
    label: 'Moderate Rain Showers',
    category: 'rain',
    icon: 'CloudRain',
    bgGradientLight: 'from-sky-100 via-blue-50 to-white',
    bgGradientDark: 'from-sky-100 via-blue-50 to-white',
    cardBg: 'bg-sky-100 border-sky-300 text-[#0D0D0D]',
  },
  82: {
    code: 82,
    label: 'Violent Rain Showers',
    category: 'rain',
    icon: 'CloudRainWind',
    bgGradientLight: 'from-blue-200/60 via-slate-100 to-white',
    bgGradientDark: 'from-blue-200/60 via-slate-100 to-white',
    cardBg: 'bg-blue-100 border-blue-400 text-[#0D0D0D]',
  },
  85: {
    code: 85,
    label: 'Slight Snow Showers',
    category: 'snow',
    icon: 'CloudSnow',
    bgGradientLight: 'from-sky-100/50 via-slate-50 to-white',
    bgGradientDark: 'from-sky-100/50 via-slate-50 to-white',
    cardBg: 'bg-sky-50 border-sky-200 text-[#0D0D0D]',
  },
  86: {
    code: 86,
    label: 'Heavy Snow Showers',
    category: 'snow',
    icon: 'Snowflake',
    bgGradientLight: 'from-sky-200/50 via-slate-100 to-white',
    bgGradientDark: 'from-sky-200/50 via-slate-100 to-white',
    cardBg: 'bg-sky-100 border-sky-300 text-[#0D0D0D]',
  },
  95: {
    code: 95,
    label: 'Thunderstorm',
    category: 'thunderstorm',
    icon: 'CloudLightning',
    bgGradientLight: 'from-purple-100/60 via-slate-100 to-white',
    bgGradientDark: 'from-purple-100/60 via-slate-100 to-white',
    cardBg: 'bg-purple-100 border-purple-300 text-[#0D0D0D]',
  },
  96: {
    code: 96,
    label: 'Thunderstorm with Hail',
    category: 'thunderstorm',
    icon: 'CloudLightning',
    bgGradientLight: 'from-purple-200/60 via-slate-100 to-white',
    bgGradientDark: 'from-purple-200/60 via-slate-100 to-white',
    cardBg: 'bg-purple-100 border-purple-400 text-[#0D0D0D]',
  },
  99: {
    code: 99,
    label: 'Heavy Hail Thunderstorm',
    category: 'thunderstorm',
    icon: 'CloudLightning',
    bgGradientLight: 'from-purple-300/50 via-slate-100 to-white',
    bgGradientDark: 'from-purple-300/50 via-slate-100 to-white',
    cardBg: 'bg-purple-200 border-purple-500 text-[#0D0D0D]',
  },
};

export function getWmoInfo(code: number): WMOInfo {
  return (
    WMO_MAP[code] || {
      code,
      label: 'Weather Variable',
      category: 'cloudy',
      icon: 'Cloud',
      bgGradientLight: 'from-slate-100 via-slate-50 to-white',
      bgGradientDark: 'from-slate-100 via-slate-50 to-white',
      cardBg: 'bg-slate-100 border-slate-300 text-[#0D0D0D]',
    }
  );
}
